name: 'Terraform Plan'

on:
  push:
    branches:
      - '!main' # excludes main

permissions:
  id-token: write
  contents: read

jobs:
  # Generates a list of folders that are used as a matrix to cycle through
  Generate-Matrix:
    name: 'Generate-Matrix'
    runs-on: ubuntu-latest
    environment: production
    outputs:
      dirs: ${{ steps.read-folders.outputs.dirs }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: read-folders
      run: |
        cd ./terraform
        folders=$(ls | grep -v modules | perl -e 'use JSON; @in=grep(s/\n$//, <>); print encode_json(\@in)."\n";')
        echo "dirs=$folders" >> "$GITHUB_OUTPUT"

  InitFmtPlan:
    needs: Generate-Matrix
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.Generate-Matrix.outputs.dirs) }} # Reads folders in the terraform directory (excluding modules) and runs a task for each one
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Config Terraform plugin cache
      run: |
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
        mkdir --parents ~/.terraform.d/plugin-cache

    - name: Cache Terraform
      uses: actions/cache@v3
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    # Connect to Azure using OIDC
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      env: 
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}   
        ARM_USE_OIDC: true
      run: |
        cd ./terraform/${{ matrix.directory }}
        terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: |
        cd ./terraform/${{ matrix.directory }}   
        terraform fmt -check

    # Generates an execution plan for Terraform and applies
    - name: Terraform Apply
      env: 
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true
      run: |
        cd ./terraform/${{ matrix.directory }}   
        terraform plan

